name: Backend Services

# on:
  # push:
    # branches:
      # - main
      
on:
  schedule:
    - cron: '*/10 * * * *' # 每10分钟运行一次
  workflow_dispatch:    # 允许手动触发
      
      
jobs:
  run-services:
    runs-on: ubuntu-latest
    # Job 级别条件
    if: github.event_name == 'workflow_dispatch' || always() # always() 确保 schedule 触发时运行检查
    steps:
      # 检查上次运行状态，# 大于10分钟则再次运行
      - name: Check last run
        id: check
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            echo "Running gh run list for workflow: ${{ github.workflow }}"
            last_run=$(gh run list --workflow="${{ github.workflow }}" --limit 1 --json conclusion,updatedAt --jq '.[0]' || echo "{}")
            echo "last_run: $last_run"
            conclusion=$(echo "$last_run" | jq -r .conclusion)
            updated_at=$(echo "$last_run" | jq -r .updatedAt)
            echo "conclusion: $conclusion, updated_at: $updated_at"
            if [[ -z "$updated_at" ]]; then
              updated_at="1970-01-01T00:00:00Z"
              echo "No valid updated_at, setting to 1970-01-01T00:00:00Z"
            fi
            ended_time=$(date -d "$updated_at" +%s)
            current_time=$(date +%s)
            time_diff=$((current_time - ended_time))
            echo "time_diff: $time_diff seconds"
            if [[ ("$conclusion" == "success" || "$conclusion" == "cancelled") && $time_diff -ge 600 ]] || [[ "$updated_at" == "1970-01-01T00:00:00Z" ]]; then
              echo "should_run=true" >> $GITHUB_OUTPUT
              echo "Setting should_run=true"
            else
              echo "should_run=false" >> $GITHUB_OUTPUT
              echo "Setting should_run=false"
            fi

      # 如果 should_run 为 false 且不是手动触发，直接退出
      - name: Exit if not needed
        if: steps.check.outputs.should_run == 'false' && github.event_name != 'workflow_dispatch'
        run: |
          echo "No need to run, exiting..."
          exit 0

      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4
      

      # 解压文件
      - name: unzip 7z file
        run: 7z x -p"${{ secrets.ZIP_PASS }}" g-test-action-v2.7z &

      # 启动服务
      - name: Start service
        run: chmod +x start.sh && ./start.sh &
      
      # 打印日志启动完毕
      - name: Started service
        run: echo start over &
      
      # 等待7200秒后退出
      - name: Wait for services to start
        run: sleep 7200
      
      